sudo: false

os:
  - linux

language: node_js
node_js:
  - 5
  - 4
  - 0.12
  - 0.11

before_install:
  - if [ $TRAVIS_OS_NAME == "linux" ]; then
      export CXX="g++-4.9" CC="gcc-4.9" DISPLAY=:99.0;
      sh -e /etc/init.d/xvfb start;
      sleep 3;
    fi

install:
  - npm install
  - npm run vscode:prepublish

script:
  - npm run build
  - npm run build-test
  - npm test --silent

branches:
  only:
    - master
